export const products = [
    {
      id: 1,
      title: "Rex 3-Seater Leather Sofa (Black)",
      description: "Meet Rex, the couch that's here to redefine class.",
      price: "659",
      img: "https://p.rmjo.in/productSquare/h1uwy1tr-500x500.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Latte Wooden Coffee Table",
      description: "Serving multiple purposes",
      price: "300",
      img: "https://5.imimg.com/data5/XZ/TB/BK/SELLER-6055679/k9onnf4y-1024x512-1000x1000.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Felix 1-Seater Fabric Sofa (Blue)",
      description: "Elegance meets comfort with the plush Felix Couch.",
      price: "479",
      img: "https://p.rmjo.in/productSquare/nodkb0rc-500x500.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Caramel 4-Seater Coffee Table (Blue)",
      description: "This table seamlessly blends with any home decor.",
      price: "629",
      img: "https://p.rmjo.in/productSquare/0i5hz5qq-500x500.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Downey Wooden Bar Unit",
      description: "For your collection of best decanters and liqueurs.",
      price: "2500",
      img: "https://p.rmjo.in/productSquare/wxtx0d6e-500x500.jpg ",
      quantity: 1,
    },
    {
      id: 6,
      title: "Rowling Bookshelf Large",
      description: "Find artistic inspiration in the art of order with this.",
      price: "369",
      img: "https://p.rmjo.in/productSquare/tt68cpfm-500x500.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Queen Spring Mattress (6x5)",
      description: "This mattress is perfect to bring out that aesthetic touch.",
      price: "529",
      img: "https://p.rmjo.in/productSquare/gfrxanei-500x500.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "Napster Metal Queen Bed (6x5)",
      description: "Find ultimate peace with Napster Bed",
      price: "900",
      img: "https://cdn.rentickle.com/media/catalog/product/cache/1/thumbnail/1024x576/b58515f018eb873dafa430b6f9ae0c1e/d/e/dede.png",
      quantity: 1,
    },
    {
      id: 9,
      title: "Betty Dresser with Stool",
      description: "The Betty dresser is perfect to hold your vanity essentials.",
      price: "299",
      img: "https://p.rmjo.in/productSquare/0jw4x00m-500x500.jpg",
      quantity: 1,
    },
  ];